### ISSUE TITLE
invalid syntax error

### ISSUE THREAD

**Issue by robertoimai** [esrlabs/git-repo#1]
I followed the instructions and was not able to get it working.
When running "repo init -u https://android.googlesource.com/platform/manifest", I get the following error message:
$ repo init -u https://android.googlesource.com/platform/manifest
  File "c:/Users/Owner/bin/repo", line 185
    print("fatal: invalid branch name '%s'" % branch, file=sys.stderr)
                                                          ^
SyntaxError: invalid syntax

**Comment by errorsolve** [comment]
All Possible Solution Added Here [SyntaxError: invalid syntax to repo init in the AOSP code in Python](https://exerror.com/syntaxerror-invalid-syntax-to-repo-init-in-the-aosp-code-in-python/)

**Comment by exeptionerror** [comment]
[Here Is All Possible Solution added at one place **SyntaxError: invalid syntax to repo init in the AOSP code**](https://exerror.com/syntaxerror-invalid-syntax-to-repo-init-in-the-aosp-code/)
