### ISSUE TITLE
Syntax error on repo init

### ISSUE THREAD

**Issue by AkshayRaj** [esrlabs/git-repo#18]
OK, I get the following error when I try to run repo on windows -->

C:\Users\Akshayraj>repo
  File "c:/Users/Akshayraj/bin/repo", line 185
    print("fatal: invalid branch name '%s'" % branch, file=sys.stderr)
                                                          ^
SyntaxError: invalid syntax

**Comment by mputz86** [comment]
Should be gone on the stable branch with the resync to google git-repo and the Python2.7+ support. Thank you very much!

**Comment by Mikdadali** [comment]
how @mputz86
