### ISSUE TITLE
Errors on 2nd run with Git 2 on Windows

### ISSUE THREAD

**Issue by bviktor** [esrlabs/git-repo#22]
Repo is from Git HEAD, [Git 2](https://github.com/git-for-windows/git/releases/) version is 2.4.5.1.

On the first run (empty workspace) the Jenkins jobs run correctly using repo, but on 2nd run (i.e. workspace is already initialized), it always produces errors like this:

    [vs2013] $ /jenkins/tools/utils/repo.cmd sync -d -c -q
    error: unable to create directory for .git/logs/HEAD
    fatal: update_ref failed for ref 'HEAD': Cannot update the ref 'HEAD'.
    error: unable to create directory for .git/logs/HEAD
    fatal: update_ref failed for ref 'HEAD': Cannot update the ref 'HEAD'.

It never happens using Git 1 shell (1.9.5). Any ideas?

**Comment by mputz86** [comment]
Tried to fix this for branch stable, but not reproducible with Git 1 and Git 2.5.2 there anymore. Could you retry and issue this problem again if it is still present in your setup?
Thank you very much!

**Comment by bviktor** [comment]
Thanks for the response. Actually sometim ago I had to revert to Git 2 and didn't receive any complaints this time, so I assume it is indeed fixed now. I'll let you know if I face this again, thanks.
