### ISSUE TITLE
"TypeError: can't use a string pattern on a bytes-like object"  on init

### ISSUE THREAD

**Issue by BrunoVernay** [esrlabs/git-repo#24]
On Linux, I am using: 
* repo script VERSION = (1, 19, 1)
* python3 --version
* Python 3.4.3

/opt/bin/repo init -u ssh://server.company.com:123456/chose_manifest
Traceback (most recent call last):
  File "/opt/bin/repo", line 709, in <module>
    main(sys.argv[1:])
  File "/opt/bin/repo", line 675, in main
    _Init(args)
  File "/opt/bin/repo", line 207, in _Init
    _Clone(url, dst, opt.quiet)
  File "/opt/bin/repo", line 459, in _Clone
    if _DownloadBundle(url, local, quiet):
  File "/opt/bin/repo", line 381, in _DownloadBundle
    m = re.compile(r'^url\.(.*)\.insteadof (.*)$').match(line)
TypeError: can't use a string pattern on a bytes-like object

I added some debug and it looks like the issue is linked to my ~/.gitconfig 
> [url "https://BrunoVernay@github.com"]
> 	insteadOf = https://github.com

Debug: url=https://github.com/esrlabs/git-repo/clone.bundle
Debug: line=b'url.https://BrunoVernay@github.com.insteadof https://github.com\n'

**Comment by mputz86** [comment]
Thanks for the report!
Could you try to reproduce this with the repo Version on the stable branch? This is a more up-to-date and a more close to google repo version - which mainly requires to use Python 2.7+ . There were multiple issues regarding the string/bytes error in our old python3 repo version which you just observed.

**Comment by BrunoVernay** [comment]
Using the stable branch, I have another error:
fatal: Cannot get https://BrunoVernay@github.com/esrlabs/git-repo/clone.bundle
fatal: error Tunnel connection failed: 400 Bad request

As a work around, I temporarily commented out the "insteadOf" option in my gitconfig and it worked.

**Comment by mputz86** [comment]
So you have followed the instructions on https://github.com/esrlabs/git-repo/tree/stable and get the "fatal" error you postet?
Could you please describe the commands you executed so I can reproduce the issue? What

And you are right, the stable version should work exactly like the official google repo! That is the overall aim :).

**Comment by BrunoVernay** [comment]
Yes, as I said the 2 lines in the ~/.gitconfig trigger the issue in the stable 1.21 version.
I made the test again with the stable version and the Android version. The Android 1.22 version is working fine. Before each test, I removed the .repo and the ~/.repo*

**Comment by mputz86** [comment]
And you replaced the "bin/repo" as well with the stable one? (just making sure :) hope to find the time to reproduce it ;))

**Comment by mputz86** [comment]
So: The issue we have here is manifold:
1) our repo is located on github, therefore the 'insteadOf' rule is applied
2) we have no clone bundle, therefore the test of the repo-script should fail, but within the check for the clone bundle..
3) is urllib.urlopen(..) called and apparently this method has a problem with the "username@host" syntax and throws a kind of host-not-found exception (whereas wget for example returns the expected 404), which repo assumes to be a failed clone bundle request
