### ISSUE TITLE
Is it alive again? Are there any new adopters?

### ISSUE THREAD

**Issue by timofonic** [esrlabs/git-repo#29]
I'm curious about different development approachs. Repo was used by a very large organization, so it should have certain interesting concepts.

Did Google abandon it? What are they using now?

**Comment by timofonic** [comment]
They still continue to develop it...

https://gerrit.googlesource.com/git-repo/

**Comment by mputz86** [comment]
hello timofonic,
yes, true, google is still providing updates for repo. And, as you can see on the stable branch, we try to keep up-to-date with the google repo.
So the latest 1.12.32 tag is merged into our version on the stable branch. We are still in the progress to move from the master branch to the more current stable branch, but highly recommend the stable branch for new projects.
Thank you very much for your comment! Is there any question still unanswered? :)

**Comment by mputz86** [comment]
So could you just reopen another issue if I missed something :). Thank you very much ! :)
