### ISSUE TITLE
Commit hook symlinks based on location in projects instead of project-objects

### ISSUE THREAD

**Issue by here-abarany** [esrlabs/git-repo#30]
The commit hooks are currently based on the projects directory rather than the project-objects directory. As a result, if the gerrit path and manifest path don't match, the commit hook symlinks are incorrect.

I have attached a patch that resolves the issue.
[patch.txt](https://github.com/esrlabs/git-repo/files/86733/patch.txt)

**Comment by mputz86** [comment]
Thank you for finding the bug and providing a patch. I will try to reproduce the issue and then apply your patch.

**Comment by Lani** [comment]
Hi,

After doing:
$ repo init -u <repository> -b <branch>
$ repo sync
$ cd projA
$ git checkout master
$ repo start <new-feature> .
$ git add .
$ git commit -m "new feature"

We get: 
"error: cannot spawn .git/hooks/commit-msg: No such file or directory"

I've managed to investigate that my repo root folder "C:\Code\Customers\CustA" has a  ".git\hooks\commit-msg.symlink" file. Which points to "C:\Code\Customers\repo\hooks\commit-msg", which doesn't exist.

I guess that it should point to "C:\Code\Customers\CustA\.repo\repo\hooks\commit-msg", which does exist.

Is this related to this patch? In that case, are there any plans for applying the patch?

**Comment by Lani** [comment]
I have now tested the patch provided by @here-abarany. I can confirm that this also solves the problem described in my previous comment. 

Are there any plans for including this patch and making a new official release?

**Comment by mputz86** [comment]
Thanks again to @Lani for testing and for @here-abarany for finding and providing a fix!
