### ISSUE TITLE
Can't sync after initializing mirror repo

### ISSUE THREAD

**Issue by vladisld** [esrlabs/git-repo#4]
'repo sync' fails on repository initialized with --mirror option.

The failure stack is:

$ repo sync
Traceback (most recent call last):
  File "c:\test\.repo\repo/main.py", line 532, in <module>
    result = _Main(sys.argv[1:])
  File "c:\test\.repo\repo/main.py", line 505, in _Main
    result = repo._Run() or 0
  File "c:\test\.repo\repo/main.py", line 158, in _Run
    result = cmd.Execute(copts, cargs)
  File "c:\test\.repo\repo\subcmds\sync.py", line 584, in Execute
    submodules_ok=opt.fetch_submodules)
  File "c:\test\.repo\repo\command.py", line 188, in GetProjects
    result.sort(key=_getpath)
TypeError: unorderable types: str() < NoneType()

$ python --version
Python 3.3.2

It caused during sort of projects list inside command.py:Command class, where some of the projects have no relpath defined.  

command.py:

def GetProjects(self, args, missing_ok=False, submodules_ok=False):
        .....
        def _getpath(x):
            return x.relpath

        result.sort(key=_getpath)

Such projects ( git-repo and manifest project ) are specifically added to the list during manifest load if mirror option is used: 

manifest_xml.py:

 def _Load(self):
    ...
    if self.IsMirror:
                    self._AddMetaProjectMirror(self.repoProject)
                    self._AddMetaProjectMirror(self.manifestProject)

_AddMetaProjectMirror specifically adds projects with relpath set to None.

**Comment by mputz86** [comment]
Thanks you, I will try to reproduce this on the stable branch.

**Comment by mputz86** [comment]
Soooo, I've tried to reproduce it on the current stable branch (ie our new repo version) and could not reproduce your error. Neither on linux nor on windows. If you can still observe the bug, please dont hesitate to reopen this issue!
Thank you very much.
