### ISSUE TITLE
branch parsing does not take under consideration windows line endings in Project.GetHead

### ISSUE THREAD

**Issue by amirhadar** [esrlabs/git-repo#41]
In Project.py the function GetHead returns line[:-1]
which suppose to get rid of the \n however in windows the line ending might be \r\n which cause the \r to remain in the branch name.

need to be changed to use strip().

Regards
Amir Hadar

**Comment by fzbassman** [comment]
+1  It would certainly resolve the problem I'm seeing using Jenkins, repo and windows

**Comment by fzbassman** [comment]
The line 'return line[5:-1]' needs strip() as well.

**Comment by mputz86** [comment]
Merged, many thanks for your help on this !
