### ISSUE TITLE
Alternative to using "more" for GIT_PAGER

### ISSUE THREAD

**Issue by rpaquay** [esrlabs/git-repo#43]
In the readme.md documentation, the section about "I can not see any colors for repo status" mentions that overriding git-pager with "more" should solve the problem.

In my particular case, that did not work, because I don't have a version of "more" available anywhere (other than in "C:\Windows\System32"). So, when I set GIT_PAGER=more, I get the following error during "repo status":

```
  File "C:\python_27_amd64\files\lib\subprocess.py", line 679, in __init__
    errread, errwrite)
  File "C:\python_27_amd64\files\lib\subprocess.py", line 896, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

I found out that an alternative to using a custom GIT_PAGER program is to set the LESS environment variable like this

```
SET LESS=-r
```

This tells `less` to stop escaping ansi sequences, leaving them untouched, so that the console subsystem has a chance to process and interpret them.

My suggestion is to either
- Update the FAQ section to mention this alternative
- Or update "repo" to allow passing "-r" to less by default

**Comment by mputz86** [comment]
Thanks for your detailed analysis, much better than using more ;) ! Merged on stable, thanks.
