### ISSUE TITLE
fatal: Cannot get https://github.com/esrlabs/git-repo/clone.bundle (error 406)

### ISSUE THREAD

**Issue by spate** [esrlabs/git-repo#49]
Started seeing this on Dec 6 when running repo init:

fatal: Cannot get https://github.com/esrlabs/git-repo/clone.bundle
fatal: HTTP error 406

Any ideas?

**Comment by ppcrong** [comment]
I get the same error when running repo init

**Comment by nkrylov** [comment]
ppcrong: you can manually apply the fix that James referenced in his comment to your ~/bin/repo. It's one line change and it fixed the problem for me.
Nikita

**Comment by ppcrong** [comment]
Hi Nikita,
Yes, I've already fixed that on my ~/bin/repo.
Thanks.
ppcrong

**Comment by mputz86** [comment]
Thank you all for your help ! Merged the fix :).
