### ISSUE TITLE
repo is trying to use a weird command

### ISSUE THREAD

**Issue by MaximilianGaedig** [esrlabs/git-repo#83]
Microsoft Windows [Version 10.0.19041.153]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\maxim>repo

C:\Users\maxim>■
'■' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\maxim>repo

C:\Users\maxim>■
'■' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\maxim>repo

C:\Users\maxim>■
'■' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\maxim>repo.cmd

C:\Users\maxim>■
'■' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\maxim>

**Comment by szymor** [comment]
I have the same issue. Is there any update on that?

BTW, commands for Windows Powershell seem not to be valid - curl under Powershell is an alias for Invoke-WebRequest which does not return downloaded data but some metadata. This output needs to be further processed by "Select-Object -ExpandProperty Content" to get the downloaded scripts.
